export const mockUser = {
  id: "user-1",
  name: "Demo User",
  email: "demo@devstash.io",
  image: "https://github.com/shadcn.png",
  isPro: true,
};

export const mockItemTypes = [
  { id: "type-1", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type-2", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type-3", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type-4", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type-5", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type-6", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type-7", name: "link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col-1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    colorClass: "border-l-blue-500",
    activeTypes: ["type-1", "type-4", "type-7"]
  },
  {
    id: "col-2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 6,
    colorClass: "border-l-cyan-500",
    activeTypes: ["type-1", "type-4"]
  },
  {
    id: "col-3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    colorClass: "border-l-zinc-600",
    activeTypes: ["type-5", "type-4"]
  },
  {
    id: "col-4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    colorClass: "border-l-amber-500",
    activeTypes: ["type-4", "type-1", "type-7", "type-2"]
  },
  {
    id: "col-5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    colorClass: "border-l-orange-500",
    activeTypes: ["type-3", "type-4"]
  },
  {
    id: "col-6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    colorClass: "border-l-violet-500",
    activeTypes: ["type-2", "type-1", "type-4"]
  },
];

export const mockItems = [
  {
    id: "item-1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "TEXT",
    content: "export function useAuth() {\n  return useContext(AuthContext);\n}",
    language: "typescript",
    typeId: "type-1",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    createdAt: "2026-01-14T10:00:00.000Z",
  },
  {
    id: "item-2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "TEXT",
    content: "async function fetchWithRetry(url: string, options?: RequestInit) { ... }",
    language: "typescript",
    typeId: "type-1",
    isFavorite: true,
    isPinned: true,
    tags: ["api", "error-handling"],
    createdAt: "2026-01-13T10:00:00.000Z",
  },
  {
    id: "item-3",
    title: "Code Review Prompt",
    description: "Prompt for AI code reviews",
    contentType: "TEXT",
    content: "You are an expert developer. Review the following code for bugs, performance issues, and readability improvements...",
    typeId: "type-2",
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "code-review"],
    createdAt: "2026-01-12T10:00:00.000Z",
  },
  {
    id: "item-4",
    title: "git reset --hard HEAD~1",
    description: "Reset to previous commit (destructive)",
    contentType: "TEXT",
    content: "git reset --hard HEAD~1",
    language: "bash",
    typeId: "type-3",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "reset"],
    createdAt: "2026-01-11T10:00:00.000Z",
  },
  {
    id: "item-5",
    title: "useLocalStorage Hook",
    description: "Persistent state management with localStorage",
    contentType: "TEXT",
    content: "export function useLocalStorage<T>(key: string, initial: T) { ... }",
    language: "typescript",
    typeId: "type-1",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks", "storage"],
    createdAt: "2026-01-10T10:00:00.000Z",
  },
  {
    id: "item-6",
    title: "Docker Compose Up",
    description: "Start containers in detached mode with rebuild",
    contentType: "TEXT",
    content: "docker compose up -d --build",
    language: "bash",
    typeId: "type-3",
    isFavorite: true,
    isPinned: false,
    tags: ["docker", "devops"],
    createdAt: "2026-01-09T10:00:00.000Z",
  },
  {
    id: "item-7",
    title: "Explain Code Prompt",
    description: "AI prompt for code explanations",
    contentType: "TEXT",
    content: "Explain the following code in simple terms, including time and space complexity...",
    typeId: "type-2",
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "learning"],
    createdAt: "2026-01-08T10:00:00.000Z",
  },
  {
    id: "item-8",
    title: "Meeting Notes Template",
    description: "Markdown template for meeting notes",
    contentType: "TEXT",
    content: "# Meeting Notes\n\n## Attendees\n\n## Agenda\n\n## Action Items",
    typeId: "type-4",
    isFavorite: false,
    isPinned: false,
    tags: ["template", "meetings"],
    createdAt: "2026-01-07T10:00:00.000Z",
  },
];
